# Generated by Django 3.1.2 on 2020-11-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_cart_items'),
        ('cart', '0002_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
