# Generated by Django 3.1.2 on 2020-11-10 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_product_author'),
        ('cart', '0003_orders_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('decrement_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_decrement_quantity', to='product.product')),
                ('increment_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_increment_quantity', to='product.product')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_products_in_cart', to='product.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cart_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
