# Generated by Django 3.1.2 on 2020-11-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201108_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_items',
        ),
    ]
