export const screenSizeBreakPoint = 680;

export const SET_TOKEN = 'SET_TOKEN';
export const SET_PRODUCTS_ALL = 'SET_POSTS_ALL_CHRONOLOGICAL_ORDER';
export const CREATE_NEW_PRODUCT = 'CREATE_NEW_POST';
export const ADD_TO_CART = 'ADD_PRODUCT_TO_SHOPPING_CART';
export const REMOVE_FROM_CART = 'REMOVE_PRODUCT_FROM_SHOPPING_CART';
export const TOGGLE_CART_VIEW = 'TOGGLE_SHOW_NOT_SHOW_SHOPPING_CART';
